### ISSUE TITLE
Anmeldung vor dem QIS System

### ISSUE THREAD

**Issue by khvostroman** [MrKrisKrisu/Hochschule-Hannover-Pruefungsergebnischecker#8]
Guten Tag,

vielen Dank für das bereitgestellte Script.
Habe eine Frage dazu.
Meine Hochschule (Hochschule Trier) leitet mich beim aufrufen des QIS-Links (qis.hochschule-trier.de) erst an eine andere Anmeldeseite (https://idp.fh-trier.de/idp/profile/SAML2/Redirect/SSO?execution=e1s1)

Ist es möglich diese Anmeldung ebenfalls in das Script zu implementieren? Leider habe ich null Ahnung von Python.

Vielen Dank im Voraus.

**Comment by MrKrisKrisu** [comment]
Moin!

Das ist für mich als Außenstehenden ohne Zugang zum System etwas schwer blind zu programmieren. Daher kann ich da wahrscheinlich eher nicht direkt helfen, sorry! :/

Falls die Linkbezeichnungen identisch sind, reicht es ggfs. aus, wenn du die Links im Script abänderst.

**Comment by khvostroman** [comment]
Alles klar, vielen Dank, das ist  natürlich verständlich wenn Sie da nicht weiter helfen können. Ich bin echt einfach leid ständig nach den Noten zu schauen, vor allem ohne Ahnung von Python. Vielen Dank für die Antwort

**Comment by khvostroman** [comment]
Die links sind eventuell gleich, jedoch habe ich halt die Anmeldung vor dem QIS System im Weg
