### ISSUE TITLE
FileNotFound Error

### ISSUE THREAD

**Issue by Nilsne** [MrKrisKrisu/Hochschule-Hannover-Pruefungsergebnischecker#9]
Hi, ich bekomme beim Ausführen des Skriptes den Error FileNotFoundError: [Errno 2] No such file or directory: 'examcheck.txt'
Brauche ich die Datei? Wenn ich sie selbst im Verzeichnis anlege, wird dort ein Hash generiert und das Skript läuft durch aber ich bekomme keine Notenübersicht per Telegram

**Comment by MrKrisKrisu** [comment]
> Nilsne closed this 31 minutes ago

Hast du es zum laufen bekommen?

**Comment by Nilsne** [comment]
Ja hat sich erledigt. Hab die Datei im gleichen Verzeichnis erstellt, nach kurzer Verzögerung kamen dann die Noten. Starkes Skript!
